### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by pannous** [galeone/dynamic-training-bench#1]

**Comment by galeone** [comment]
In the next few days I'm going to update the `README.md` file with an explanation. I'll update this issue when the file is ready, so you'll get notified.

**Comment by galeone** [comment]
@pannous I've updated the `README.md` file with an explanation. Let me know if it's clear and helped you to understand how to use DTB.

**Comment by galeone** [comment]
I upgraded DTB and renamed it to DyTB: now it's both Python library and a CLI tool.
The python library can be installed via pip: `pip install dytb`.

The README should be enough to understand how to use it as a CLI tool or a library.
I'm going to close this issue. If you have any question feel free to comment here or open a new issue.
