### ISSUE TITLE
SingleLayerCAE fails

### ISSUE THREAD

**Issue by wingz1** [galeone/dynamic-training-bench#17]
Hi, I'm having a similar problem to the last one I got when running an example model:
Any ideas?  Thanks!

dytb_train --model SingleLayerCAE --dataset MNIST --optimizer AdamOptimizer --optimizer_args '{"learning_rate": 1e-5}' --train_device "/gpu:1" --batch_size 1024 --l2_penalty 1e-9
Extracting ...anaconda3/lib/python3.6/site-packages/dytb/inputs/predefined/data/MNIST/train-images-idx3-ubyte.gz
Extracting ...anaconda3/lib/python3.6/site-packages/dytb/inputs/predefined/data/MNIST/train-labels-idx1-ubyte.gz
Extracting ...anaconda3/lib/python3.6/site-packages/dytb/inputs/predefined/data/MNIST/t10k-images-idx3-ubyte.gz
Extracting ...anaconda3/lib/python3.6/site-packages/dytb/inputs/predefined/data/MNIST/t10k-labels-idx1-ubyte.gz
Args: {   'batch_size': 1024,
    'checkpoint_path': '',
    'comment': '',
    'dataset': 'MNIST',
    'epochs': 150,
    'exclude_scopes': None,
    'l2_penalty': 1e-09,
    'lr_decay': False,
    'lr_decay_epochs': 25,
    'lr_decay_factor': 0.1,
    'model': 'SingleLayerCAE',
    'optimizer': 'AdamOptimizer',
    'optimizer_args': {'learning_rate': 1e-05},
    'restart': False,
    'train_device': '/gpu:1',
    'trainable_scopes': None}
Traceback (most recent call last):
  File "...anaconda3/bin/dytb_train", line 66, in <module>
    sys.exit(main())
  File "...anaconda3/bin/dytb_train", line 56, in main
    comment=ARGS.comment)
  File "...anaconda3/lib/python3.6/site-packages/dytb/train.py", line 217, in train
    return Trainer(model, dataset, args, steps, paths).train()
  File "...anaconda3/lib/python3.6/site-packages/dytb/trainer/Trainer.py", line 76, in train
    l2_penalty=self._args["regularizations"]["l2"])
TypeError: get() got multiple values for argument 'train_phase'

**Comment by galeone** [comment]
Hi! I can't reproduce your error but while I was trying to run your example I found out another error that I fixed. Maybe this fix could solve your problem too.

Update dytb to the new version and let me know if it's solved!

**Comment by wingz1** [comment]
Yes, that seems to solve it, thanks!

**Comment by galeone** [comment]
You're welcome!
