### ISSUE TITLE
Syntax Error on Python 3.4 for merging dict into another using **

### ISSUE THREAD

**Issue by vivekk0903** [galeone/dynamic-training-bench#19]
Trying to run the example present [here](https://github.com/galeone/dynamic-training-bench/blob/master/examples/VGG-Cifar10-100-TransferLearning-FineTuning.ipynb), but this line:

https://github.com/galeone/dynamic-training-bench/blob/master/dytb/train.py#L202

throws a syntax error in python 3.4. On checking the reason, I got to know that [this syntax is supported](https://stackoverflow.com/a/26853961/3374996) only from 3.5 python.

This was confusing because in the [description its written](https://github.com/galeone/dynamic-training-bench/blob/master/README.md#dynamic-training-bench-dytb) that dytb is compatible with Python 3.4

Please correct the code.

**Comment by galeone** [comment]
I'd correct the README instead. The unpack generalization I use has been introduced in Python 3.5 and not in python 3.4: https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-448

Thank you for pointing this out!

To run the example, just use python 3.5 (it's easy to create a virtualenv with any python version you need, hence go with 3.5 or better 3.6)
